import type { Metadata } from "next";
import { Handjet } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const handjet = Handjet({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Zacky Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={handjet.className}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
